# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
commands:
    print_pipeline_id:
      description: "Simple command to print pipeline ID"
      steps:  
        - run: echo ${CIRCLE_WORKFLOW_ID}
        
jobs:
  say-hello:
    # Specify the execution environment. You can specify an image from Dockerhub or use one of our Convenience Images from CircleCI's Developer Hub.
    # See: https://circleci.com/docs/2.0/configuration-reference/#docker-machine-macos-windows-executor
    docker:
      - image: cimg/base:stable
    # Add steps to the job
    # See: https://circleci.com/docs/2.0/configuration-reference/#steps
    steps:
      - checkout
      - run:
          name: "Say hello"
          command: "echo Hello, World!"

  say-name:
    docker:
        - image: cimg/base:stable
    steps:
      - checkout
      - run:
          name: "My Name"
          command: "echo $MY_NAME"
  
  save_hello_world_output:
    docker:
        - image: cimg/base:stable
    steps:
      - run: mkdir -p workspace
      - run:
          name: "Save Output"
          command: |
              echo "Hello World" > workspace/output.txt
      - persist_to_workspace:
          root: workspace
          paths: 
            - output.txt
  
  print_output_file:
    docker:
      - image: cimg/base:stable
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run: |
            cat /tmp/workspace/output.txt
  
  print_id:
    docker:
      - image: cimg/base:stable
    steps:
        - print_pipeline_id
  
workflows:
  say-hello-workflow:
    jobs:
      - print_id
      - say-hello
      - save_hello_world_output
      - print_output_file:
          requires:
            - save_hello_world_output
            